# Build-time build recipe configuration for the FireSim Simulation Manager
# See https://docs.fires.im/en/stable/Advanced-Usage/Manager/Manager-Configuration-Files.html for documentation of all of these params.

# this file contains sections that describe hardware designs that /can/ be built.
# edit config_build.yaml to actually "turn on" a config to be built when you run
# buildbitstream

###########
# Schema:
###########
# <NAME>:
#    PLATFORM: <string>
#    TARGET_PROJECT: <string>
#    TARGET_PROJECT_MAKEFRAG: <string | null>
#    DESIGN: <string>
#    TARGET_CONFIG: <string>
#    PLATFORM_CONFIG: <string>
#    deploy_quintuplet: <string | null>
#    platform_config_args:
#       fpga_frequency: <int>
#       build_strategy: <string>
#    post_build_hook: <string | null>
#    metasim_customruntimeconfig: <string | null>
#    bit_builder_recipe: <string>
#    # OPTIONAL: overrides for bit builder recipe
#    # Arg structure should be identical to the args given
#    # in the base_recipe.
#    #bit_builder_arg_overrides:
#    #  <ARG>: <OVERRIDE>

# MIDAS Examples -- BUILD SUPPORT ONLY; Can't launch driver correctly on run farm
midasexamples_gcd:
    PLATFORM: f1
    TARGET_PROJECT: midasexamples
    TARGET_PROJECT_MAKEFRAG: null
    DESIGN: GCD
    TARGET_CONFIG: NoConfig
    PLATFORM_CONFIG: DefaultF1Config
    deploy_quintuplet: null
    platform_config_args:
        fpga_frequency: 75
        build_strategy: TIMING
    post_build_hook: null
    metasim_customruntimeconfig: null
    bit_builder_recipe: bit-builder-recipes/f1.yaml

# FireAxe Tutorial Config
f1_rocket_split_soc_fast:
    PLATFORM: f1
    TARGET_PROJECT: firesim
    TARGET_PROJECT_MAKEFRAG: ../../../generators/firechip/chip/src/main/makefrag/firesim
    DESIGN: FireSim
    TARGET_CONFIG: FireSimRocketConfig
    PLATFORM_CONFIG: RocketTileF1PCIMBase
    deploy_quintuplet: null
    platform_config_args:
        fpga_frequency: 90
        build_strategy: TIMING
    post_build_hook: null
    metasim_customruntimeconfig: null
    bit_builder_recipe: bit-builder-recipes/f1.yaml

f1_rocket_split_tile_fast:
    PLATFORM: f1
    TARGET_PROJECT: firesim
    TARGET_PROJECT_MAKEFRAG: ../../../generators/firechip/chip/src/main/makefrag/firesim
    DESIGN: FireSim
    TARGET_CONFIG: FireSimRocketConfig
    PLATFORM_CONFIG: RocketTileF1PCIMPartition0
    deploy_quintuplet: null
    platform_config_args:
        fpga_frequency: 90
        build_strategy: TIMING
    post_build_hook: null
    metasim_customruntimeconfig: null
    bit_builder_recipe: bit-builder-recipes/f1.yaml

# Additional Tutorial Config (supports optional AutoCounters)
firesim_gemmini_rocket_singlecore_no_nic:
    PLATFORM: f1
    TARGET_PROJECT: firesim
    TARGET_PROJECT_MAKEFRAG: ../../../generators/firechip/chip/src/main/makefrag/firesim
    DESIGN: FireSim
    TARGET_CONFIG: FireSimLeanGemminiRocketConfig
    PLATFORM_CONFIG: WithAutoCounter_BaseF1Config
    deploy_quintuplet: null
    platform_config_args:
        fpga_frequency: 50 # conservative for now (could go higher)
        build_strategy: TIMING
    post_build_hook: null
    metasim_customruntimeconfig: null
    bit_builder_recipe: bit-builder-recipes/f1.yaml

# Additional Tutorial Config
firesim_rocket_singlecore_no_nic_l2_lbp:
    PLATFORM: f1
    TARGET_PROJECT: firesim
    TARGET_PROJECT_MAKEFRAG: ../../../generators/firechip/chip/src/main/makefrag/firesim
    DESIGN: FireSim
    TARGET_CONFIG: WithDefaultFireSimBridges_WithFireSimHighPerfConfigTweaks_chipyard.RocketConfig
    PLATFORM_CONFIG: BaseF1Config
    deploy_quintuplet: null
    platform_config_args:
        fpga_frequency: 90
        build_strategy: TIMING
    post_build_hook: null
    metasim_customruntimeconfig: null
    bit_builder_recipe: bit-builder-recipes/f1.yaml
