# Hardware config database for FireSim Simulation Manager
# See https://docs.fires.im/en/stable/Advanced-Usage/Manager/Manager-Configuration-Files.html for documentation of all of these params.

# Hardware configs represent a combination of:
#   - an agfi/bitstream_tar with the bitstream for an fpga
#   - (optional) a deployquintuplet override
#   - (optional) a deploy_makefrag_override
#   - (optional) a custom_runtime_config

# The HWDBs (and their AGFI's/bitstream_tar's) provided below are public and available to all users.

# DOCREF START: Example HWDB Entry
midasexamples_gcd:
    bitstream_tar: https://raw.githubusercontent.com/invalid/address.tar.gz
    deploy_quintuplet_override: null
    deploy_makefrag_override: null
    custom_runtime_config: null
# DOCREF END: Example HWDB Entry
f1_rocket_split_soc_fast:
    agfi: agfi-0839ac7e434ebbecf
    deploy_quintuplet_override: null
    deploy_makefrag_override: ../../../generators/firechip/chip/src/main/makefrag/firesim
    custom_runtime_config: null
f1_rocket_split_tile_fast:
    agfi: agfi-097fb61fddb61f5ce
    deploy_quintuplet_override: null
    deploy_makefrag_override: ../../../generators/firechip/chip/src/main/makefrag/firesim
    custom_runtime_config: null
firesim_gemmini_rocket_singlecore_no_nic:
    agfi: agfi-0902b022299df8be0
    deploy_quintuplet_override: null
    deploy_makefrag_override: ../../../generators/firechip/chip/src/main/makefrag/firesim
    custom_runtime_config: null
firesim_rocket_singlecore_no_nic_l2_lbp:
    agfi: agfi-02996021b15debaf4
    deploy_quintuplet_override: null
    deploy_makefrag_override: ../../../generators/firechip/chip/src/main/makefrag/firesim
    custom_runtime_config: null
